name: Release Build Kit
description: Create GitHub release for Build Kit
inputs:
  os:
    description: OS
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.os }}
        path: out/make/zip/**/*.zip
    - uses: softprops/action-gh-release@v1
      with:
        files: out/make/zip/**/*.zip
