name: Slack Block Kit
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
        with:
          os: ${{ matrix.os }}
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
        uses: ./.github/actions/release
